---
- name: Ensure SSH directory is present
  file:
    state: directory
    name: "{{ ek_ssh_dir }}"
    mode: 0700

- name: Check if SSH key exists
  stat:
    path: "{{ ek_ssh_key }}"
  register: ek_ssh_key_check

- name: Copy key into SSH directory
  copy:
    src: "{{ ek_ssh_key }}"
    dest: "{{ ek_ssh_key_file }}"
    mode: 0400
  when: ek_ssh_key_check.stat.exists == True

- name: Ensure SSH is properly configured (through proxy)
  include_tasks: ssh_with_proxy.yml
  when: ek_ssh_proxy is defined and ek_ssh_proxy != ""

- name: Ensure SSH is properly configured (without proxy)
  include_tasks: ssh_without_proxy.yml
  when: ek_ssh_proxy is not defined or ek_ssh_proxy == ""
