---
# tasks file for ekara.ssh
- name: Create .ssh
  file:
    state: directory
    name: "{{ ekara_ssh_dir }}"
    mode: 0700
- name: Check ssh file
  stat:
    path: "{{ ekara_ssh_key }}"
  register: tmp_file
- name: Push ssh key
  copy:
    src: "{{ ekara_ssh_key }}"
    dest: "{{ ekara_ssh_dir }}/{{ ekara_ssh_key | basename }}"
    mode: 0400
  when: tmp_file.stat.exists == True

- name: Add ssh configuration with proxy
  include_tasks: ssh_with_proxy.yml
  when: ekara_ssh_proxy is not none and ekara_ssh_proxy != ""

- name: Add ssh configuration without proxy
  include_tasks: ssh_without_proxy.yml
  when: ekara_ssh_proxy is none or ekara_ssh_proxy == ""
