---
- name: Update SSH config
  blockinfile:
    block: "{{ lookup('template', 'templates/proxy/ssh_config') }}"
    dest: "{{ ek_ssh_dir }}/config"
    create: true
    mode: 0400
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ ek_ssh_host }}"

- name: Generate SSH proxy authentication file
  template:
    src: "templates/proxy/auth"
    dest: "{{ ek_ssh_auth_file }}"
    mode: 0400
  when: ek_ssh_proxy_user != ""
