---
# tasks file for ekara.ssh
- name: Update ssh config
  blockinfile:
    dest: "{{ ekara_ssh_dir }}/config"
    block: "{{ lookup('template', 'templates/ssh_config') }}"
    create: true
    mode: 0400
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ ekara_ssh_host }}"
