---
# tasks file for lagoon.ssh
- name: Update ssh config
  blockinfile:
    dest: "{{ lagoon_ssh_dir }}/config"
    block: "{{ lookup('template', 'templates/ssh_config') }}"
    create: true
    mode: 0400
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ lagoon_ssh_host }}"
