---
# tasks file for ekara.ssh
- name: Set authent configuration
  set_fact:
    ekara_ssh_proxy_auth: "{{ ekara_ssh_dir }}/authent"
  when:
  - ekara_ssh_proxy_user != ""

- name: Update ssh config
  blockinfile:
    block: "{{ lookup('template', 'templates/ssh_config_proxy') }}"
    dest: "{{ ekara_ssh_dir }}/config"
    create: true
    mode: 0400
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ ekara_ssh_host }}"

- name: Generate auth config
  template:
    src: "templates/authent.j2"
    dest: "{{ ekara_ssh_proxy_auth }}"
    mode: 0400
  when: ekara_ssh_proxy_user != ""
