---
- name: Update SSH config
  blockinfile:
    dest: "{{ ek_ssh_dir }}/config"
    block: "{{ lookup('template', 'templates/no_proxy/ssh_config') }}"
    create: true
    mode: 0400
    marker: "# {mark} EKARA MANAGED BLOCK FOR '{{ ek_ssh_host }}'"
